@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.lightman314.lightmanscurrency.api.misc.item_handlers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;