@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.lightman314.lightmanscurrency.api.traders.discount_codes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;