name: Translation Upload
description: Provide a language translation of this mod
title: "Translation: LANGUAGE"
labels: [ "Translation" ]
assignees:
  - Lightman314
body:
    - type: input
      attributes:
        label: Language Name
        description: Please state the name of the language this is a translation for (for use in the Translation Info wiki page).
        placeholder: e.x. Lolcatz
      validations:
        required: true
    - type: input
      attributes:
        label: Accredation
        description: Please state the name you wish to be credited under on the Translation Info wiki page. If you do not wish to be credited, simply say "anonymous"
        placeholder: e.x. Lightman
      validations:
        required: true
    - type: textarea
      attributes:
        label: Language File
        description: Please attach the *.json language file here. DO NOT copy/paste the files contents into this form. The latest version of the english language file can be downloaded from [here](https://github.com/Lightman314/LightmansCurrency/tree/main/src/generated/resources/assets/lightmanscurrency/lang), and all other language files from [here](https://github.com/Lightman314/LightmansCurrency/tree/main/src/main/resources/assets/lightmanscurrency/lang). Please be careful to not accidentally break json formatting (extra or missing comma's or quotation marks, etc.) as it will keep your language file from working.
      validations:
        required: true
        
