name: Translation Upload
description: Request a correction or improvement to the wiki
title: "Documentation: DESCRIPTION"
labels: [ "Documentation" ]
assignees:
  - Lightman314
body:
    - type: input
      attributes:
        label: Language Name
        description: Please state the name of the language this is a translation for (for use in the Translation Info wiki page).
        placeholder: e.x. Lolcatz
      validations:
        required: true
    - type: input
      attributes:
        label: Accredation
        description: Please state the name you wish to be credited under on the Translation Info wiki page. If you do not wish to be credited, simply say "anonymous"
        placeholder: e.x. Lightman
      validations:
        required: true
    - type: textarea
      attributes:
        label: Language File
        description: Please attach the *.json language file here. DO NOT copy/paste the files contents into this form. The latest version of the language files (including the english file) can be downloaded from here. Please be careful to not accidentally break json formatting (extra or missing comma's or quotation marks, etc.) as it will keep your language file from working.
      validations:
        required: true
        
