@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.lightman314.lightmanscurrency.api.trader_interface.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;