@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package io.github.lightman314.lightmanscurrency.common.blockentity.item_handler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;