@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.lightman314.lightmanscurrency.common.crafting.durability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;