@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.lightman314.lightmanscurrency.api.trader.notifications.categories;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;