package io.github.lightman314.lightmanscurrency.util;

import java.util.List;
import java.util.stream.Collectors;

import io.github.lightman314.lightmanscurrency.network.LightmansCurrencyPacketHandler;
import io.github.lightman314.lightmanscurrency.network.message.MessageRequestNBT;
import io.github.lightman314.lightmanscurrency.LightmansCurrency;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.nbt.CompoundNBT;
import net.minecraft.network.play.server.SUpdateTileEntityPacket;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.ChunkPos;
import net.minecraft.world.World;
import net.minecraft.world.server.ServerWorld;

public class BlockEntityUtil
{
    /**
     * Sends an update packet to clients tracking a tile entity.
     * Sends the packet generated by TileEntity.getUpdatePacket, which is null by default, so be careful.
     * Received packet will be handled by IForgeTileEntity.onDataPacket, which is also null by default.
     * @param tileEntity the tile entity to update
     */
    public static void sendUpdatePacket(TileEntity tileEntity)
    {
    	SUpdateTileEntityPacket packet = tileEntity.getUpdatePacket();
        if(packet != null)
        {
            sendUpdatePacket(tileEntity.getLevel(), tileEntity.getBlockPos(), packet);
        }
        else
        {
        	LightmansCurrency.LogError(tileEntity.getClass().getName() + ".getUpdatePacket() returned null!");
        }
    }

    /**
     * Sends an update packet to clients tracking a tile entity with a specific CompoundNBT
     * Received packet will be handled by IForgeTileEntity.onDataPacket, which is null by default, so be careful.
     * @param tileEntity the tile entity to update
     */
    public static void sendUpdatePacket(TileEntity tileEntity, CompoundNBT compound)
    {
        SUpdateTileEntityPacket packet = new SUpdateTileEntityPacket(tileEntity.getBlockPos(), 99, compound);
        sendUpdatePacket(tileEntity.getLevel(), tileEntity.getBlockPos(), packet);
    }

    private static void sendUpdatePacket(World world, BlockPos pos, SUpdateTileEntityPacket packet)
    {
        if(world instanceof ServerWorld)
        {
            ServerWorld server = (ServerWorld)world;
        	//CurrencyMod.LOGGER.info("Sending Tile Entity Update Packet to the connected clients.");
            List<ServerPlayerEntity> players = server.getChunkSource().chunkMap.getPlayers(new ChunkPos(pos), false).collect(Collectors.toList());
            players.forEach(player -> player.connection.send(packet));
        }
        else
        {
        	LightmansCurrency.LogWarning("Cannot send Tile Entity Update Packet from a client.");
        }
    }
    
    public static void requestUpdatePacket(TileEntity be) {
    	requestUpdatePacket(be.getLevel(), be.getBlockPos());
    }
    
    public static void requestUpdatePacket(World level, BlockPos pos)
    {
    	if(level.isClientSide)
    		LightmansCurrencyPacketHandler.instance.sendToServer(new MessageRequestNBT(pos));
    }
    
}
